---
- name: Install Lynis security tool
  ansible.builtin.dnf:
    name:
      - lynis
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8
