---
- name: Converge
  hosts: all
  tasks:
    - name: "Include thbe.common"
      ansible.builtin.include_role:
        name: "thbe.common"
    - name: "Include thbe.rhel"
      ansible.builtin.include_role:
        name: "thbe.rhel"
      vars:
        external_repos_epel: true
    - name: "Include thbe.security"
      ansible.builtin.include_role:
        name: "thbe.security"
      vars:
        pass_max_days: 180
        pass_min_days: 10
        pass_min_len: 10
        pass_warn_age: 14
        remember: 12
        lynis_enable: true
        rkhunter_enable: true
