---
- name: Converge
  hosts: all
  collections:
    - ansible.posix
  tasks:
    - name: "Include thbe.common"
      ansible.builtin.include_role:
        name: "thbe.common"
    - name: "Include thbe.rhel"
      ansible.builtin.include_role:
        name: "thbe.rhel"
    - name: "Include thbe.security"
      ansible.builtin.include_role:
        name: "thbe.security"
      vars:
        remember: 16
