---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: RockyLinux-8
    image: rockylinux:8
    pre_build_image: true
  - name: RockyLinux-9
    image: rockylinux:9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint --list-files .
  ansible-lint -v --force-color .
