name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Molecule
        uses: gofrolist/molecule-action@v2
