name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Ansible Molecule
        uses: gofrolist/molecule-action@v2.3.17
        with:
          molecule_options: --debug
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
